### ISSUE TITLE
After scheduled run the last app isn't closed

### ISSUE THREAD

**Issue by MarkyMarkDE** [d4rken-org/sdmaid-se#624] opened 2023-09-13 18:58 UTC
After SDMaid SE scheduled run, I think it's the last app (or always the same app?) the "Tool zur Datenwiederherstellung" are not being closed again. 

With CCleaner is it the same problem, but here is Opera not being closed again. 

So I think much more, that only the last app in cleaning process is affected. 

I'm on Pixel 7 
Last Android 13 with Updates of 5th August 23
Non root

By the way: the scheduled run takes much longer than the manually run, does both runs differ in depth or something?

**Comment by MarkyMarkDE** [comment] 2023-09-18 16:35
> Can you provide a debug log?

i will try to do and will post it in discord okay?

**Comment by d4rken** [comment] 2023-09-18 16:44
Or mail it to support@ and reference the ticket number.

**Comment by MarkyMarkDE** [comment] 2023-09-18 16:47
> Or mail it to support@ and reference the ticket number.

maybe the file will be to large in size for email ...

**Comment by MarkyMarkDE** [comment] 2023-09-18 19:01
> Or mail it to support@ and reference the ticket number.

sorry, it seems that i cannot provide an debug log. My scheduler should run every 8pm and a few minutes before i start the debug logging and now at 9pm the scheduler has not runned yet.

**Comment by MarkyMarkDE** [comment] 2023-09-19 19:18
it seems that i really can't provied any debug log. yes i always start the debug logging before my scheduler should run, but in this mode the app threads complete different. I have also looked in the log, but i cannot see any unusual here. The main problem i reported is when the app runs on scheduler and when the lock screen is shown. Then I see an "overlay" with sd-maid and after the run, the last item from scanning is always open. If you can provide another way to find and solve this problem, please let me know.

**Comment by MarkyMarkDE** [comment] 2023-09-27 23:43
this bug is solved in
SDMaid-2/SE FOSS 0.13.0-beta0 👍

I do close this ticket as solved now, thank you for fixing

**Comment by MarkyMarkDE** [comment] 2023-09-29 18:51
Unfortunately this bug isn't gone, have reopen this ticket, I'm so sorry!

**Comment by MeloriTensei** [comment] 2023-10-09 15:34
Hi @MarkyMarkDE  , is it reproducible by intentionally creating a schedule just minutes after your current time and run a debug log before the scheduled task begins?

**Comment by MarkyMarkDE** [comment] 2023-10-09 15:46
> Hi @MarkyMarkDE , is it reproducible by intentionally creating a schedule just minutes after your current time and run a debug log before the scheduled task begins?

no, my schedule should run daily at 8pm and sometimes (yesterday again) the schedule has already finished and the "working overlay" is being closed. A few seconds after it start again (overlay comes up) and sometimes (yesterday too) i can click endlessly  Cancel but SDMaid SE starts and starts and starts. Here you must really kill the app complete, there is something that cause an  endless loop in scheduler.

**Comment by MeloriTensei** [comment] 2023-10-09 15:57
@MarkyMarkDE 
If it does occur "sometimes" is it possible to keep trying at random times and see if you could catch that behavior in real time.  Try to observe for a few days.

**Comment by MarkyMarkDE** [comment] 2023-10-09 19:02
[eu.darken.sdmse_logfile_1696874127636.log.zip](https://github.com/d4rken-org/sdmaid-se/files/
12849520/eu.darken.sdmse_logfile_1696874127636.log.zip)

Here you can see all results of my tickets, last app isn't closed after schedule and clicking Cancel multiple before app indeed stopped

**Comment by MarkyMarkDE** [comment] 2023-10-24 19:51
@d4rken nun kann ich auch definitiv sagen, wann das passiert.

- wenn ein Zeitplan mit Bediengshilfen gestartet wird, aber zu diesem Zeitpunkt das Display nicht aktiv und auch nicht entsperrt ist.
- Gleiches Verhalten auch, wenn man einen Job abbricht

**Comment by d4rken** [comment] 2023-12-04 09:39
> Gleiches Verhalten auch, wenn man einen Job abbricht

That's as designed. If the user cancels the action, SD Maid will not do anything else as we assume that if the user cancels an action they need to take immediate control over the device.

> wenn ein Zeitplan mit Bediengshilfen gestartet wird, aber zu diesem Zeitpunkt das Display nicht aktiv und auch nicht entsperrt ist.

But only if the accessibility service has been explicitly enabled in the settings, correct?

by default ACS should not be running via scheduler. If the user still enables it, they should know what they are doing. In this case, SD Maid can launch an activity "behind" the lock screen, but the "back button press" to close windows will be blocked by the lock screen.

Closing this for now as I think this is working as intended.

**Closed by d4rken** 2023-12-04 09:39 UTC
Labels: bug, needs info/repro 🤔, c: AppCleaner, c: Scheduler, ACS
