### ISSUE TITLE
Permission are missing

### ISSUE THREAD

**Issue by f1100** [d4rken-org/sdmaid-se#1107] opened 2024-03-31 23:04 UTC
**Describe the bug**
 The Apps part of the Appanalyzer does not work

 - Device: [Samsung galaxy tab a 2016]
 - OS: [e.g. Android 8.1]
 - Root status [No Root]
 - SD Maid 2/SE version [e.g. v0.23.0]

![Permission are missing](https://github.com/d4rken-org/sdmaid-se/assets/41730397/39cc7c7c-2ad8-485d-b532-8c547e515d9b)

**Comment by d4rken** [comment] 2024-04-02 13:47
Did you give all permissions? Notable access to usage stats? Did this exist on Android 8.1? :thinking: 

Please provide a debug log.

**Comment by d4rken** [comment] 2024-04-02 16:45
Found the cause, fixed in the next update.

**Closed by d4rken** 2024-04-02 16:45 UTC
Labels: bug, c: StorageAnalyzer
