### ISSUE TITLE
Scan specific folder(s) for duplicates and analyse space

### ISSUE THREAD

**Issue by hexman1999** [d4rken-org/sdmaid-se#1039] opened 2024-02-26 11:28 UTC
I think it will be more convenient and faster to check specific folder/ folders for duplicates rather than searching all across device by adding some include/ exclude technique like gdupes in pc

Also adding option to analyze specific folder space instead of analyzing the whole storage space 

Thanks for your great work, I appreciate

**Comment by d4rken** [comment] 2024-02-27 13:16
Dupe of #823

**Closed by d4rken** 2024-02-27 13:16 UTC
Labels: enhancement, triage
