### ISSUE TITLE
Android monet theme

### ISSUE THREAD

**Issue by mcbkan** [d4rken-org/sdmaid-se#278] opened 2023-05-14 12:15 UTC
Will there be support monet in future?

**Comment by d4rken** [comment] 2023-05-14 12:19
What is "monet theme"? Can you show give me a link or a screenshot?

**Comment by mcbkan** [comment] 2023-05-14 12:30
![yu_you2](https://github.com/d4rken-org/sdmaid-se/assets/133577298/1e212ef0-08f2-4c4c-8689-5097a725be3b)
Dynamic colors system and apps like wallpaper android 12+

**Comment by d4rken** [comment] 2023-05-14 12:40
Ah, that's "Material You" right? See #50

I will look into, but features and bugfixes are currently a higher priority.

I'm not 100% sure how to change the app design for this, how do I keep the app "brand" intact while allowing different colors.

SD Maid isn't a launcher or a "wallpaper", but a tool. Similar to SD Maid 1, I'm not yet sure how much time development time I should spend on themes. Time spend on theming is time lost on other improvements... :wink: 

Closing this ticket, duplicate of #50.

**Closed by d4rken** 2023-05-14 12:40 UTC
Labels: enhancement, needs info/repro 🤔, UI

**Comment by mcbkan** [comment] 2023-05-14 12:50
Thanks. The application is great, I agree that it is better to spend this time on finalizing the functionality, but sometime in the future, still take care of the design. Good luck! :3

**Comment by d4rken** [comment] 2023-05-14 12:56
SD Maid SE is at least already based on Material 3 design libraries, so it's not impossible to add, in SD Maid 1 this would be a huge problem :grin:.

**Comment by d4rken** [comment] 2023-05-14 12:57
Maybe I could make the Material You theme a "pro feature", then it would be possible to spend more of my time on it... :thinking:
