### ISSUE TITLE
Root permission not working with Magisk

### ISSUE THREAD

**Issue by AdamEight** [d4rken-org/sdmaid-se#1073] opened 2024-03-19 02:34 UTC
**Describe the bug**
Clear with root not working

**To Reproduce**
1. Try clean any cache with root

**Expected behavior**
When i tried to clean cache, sdmaid uses accessebility function

**Smartphone:**
 - Device: Redmi Note 9S
 - OS: Android 14
 - Root status: Rooted - Magisk Delta
 - SD Maid 2/SE version 0.22.0-beta0

**Comment by FWC-9696** [comment] 2024-03-19 13:45
I can confirm this bug and that I have properly granted Root access to the app in Magisk.

**Comment by FWC-9696** [comment] 2024-03-19 13:50
![Screenshot_20240319-093657_Magisk.png](https://github.com/d4rken-org/sdmaid-se/assets/76880537/c16a3f0d-709a-42ea-a686-632a9c5eda63)

![Screenshot_20240319-093643_SD Maid SE.png](https://github.com/d4rken-org/sdmaid-se/assets/76880537/5098b059-87d5-4ea3-bbee-175de4e03adb)

**Comment by d4rken** [comment] 2024-03-19 16:10
Possible duplicate of #1069

Can you get me a logfile?

https://github.com/d4rken-org/sdmaid-se/wiki/Bugs#debug-log

**Comment by d4rken** [comment] 2024-03-19 17:10
Log extra log is not necessary, I got it. Update soon :+1:

**Closed** 2024-03-19 18:22 UTC
Labels: bug, Root, api: 34 A14 (Upside Down Cake)
