### ISSUE TITLE
System Apps Duplicated; Cannot Be Cleaned

### ISSUE THREAD

**Issue by FWC-9696** [d4rken-org/sdmaid-se#169] opened 2023-04-13 13:59 UTC
**Describe the bug**
When Settings -> App Cleaner -> Include System Apps is selected, app cleaner will fail to clean apps with the message "Error - Illegal Argument Exception | Collection Contains More Than One Matching Element" . If "View" is selected under "App Cleaner" on the main screen, each system app is visible twice, which is likely related. See pictures

**To Reproduce**
1. Check Box Under 'Settings -> App Cleaner -> Include System Apps'
2. Click "Scan" under "App Cleaner" on the main screen
3. Click "Delete" under "App Cleaner" on the main screen

**Expected behavior**
App Cleaner should only list system apps once and should successfully clean the associated files.

**Smartphone (please complete the following information):**
 - Device: Pixel 3a
 - OS: Android 12L (LineageOS 19.1)
 - Root status: Rooted - Magisk v26.1
 - SD Maid 2/SE version: e.g. v0.7.2-rc0

**Debug log**
Unfortunately, I'm submitting this on mobile, so I can't go to the instructions link at the moment.

**Screenshots/Video**
![Screenshot_20230413-091241_SD Maid SE.png](https://user-images.githubusercontent.com/76880537/231781696-30bcacdc-27a8-487e-8e56-b7e9841a18b6.png)

![Screenshot_20230413-091250_SD Maid SE.png](https://user-images.githubusercontent.com/76880537/231781729-3e7709dc-32fe-4b0c-86fe-918906832ed2.png)

**Additional context**
N/A

**Comment by d4rken** [comment] 2023-04-13 14:39
Thanks for the good report 💯. Based on your screenshots I think this is the same cause as #163, unintended side effects from better support for multiple users on rooted devices.

I'm closing this for now, please reopen this after the next update if it is not fixed.

Note that you may have to go into settings after the next update to try to reproduce it. I'm currently leaning towards making Multiuser Support for appcleaner an opt-in feature. Seems more like a power user thing anyways, what do you think?

**Closed** 2023-04-13 14:39 UTC
Labels: bug, c: AppCleaner

**Comment by FWC-9696** [comment] 2023-04-13 14:41
Sounds great. Compliments on the app, too. It is a great foss utility and seems to be improving continuously.
