### ISSUE TITLE
QUERY_ALL_PACKAGES not granted on Samsung (Android 14)

### ISSUE THREAD

**Issue by dancorpse** [d4rken-org/sdmaid-se#1015] opened 2024-02-15 09:30 UTC
**Describe the bug**
Just install SD maid SE on my new Android 14 phone but once I click appcleaner the app stop and quit by itself right away. But it can work on my android 10 old phone. I noticed that there’s no grant access to android/data folder on Android 14.

**To Reproduce**
1. Go to 'appcleaner'
2. Click on 'appcleaner.'

**Expected behavior**
Is that because of android’s restriction to android/data folder from Android 11 on?
Any way to solve?

**Smartphone (please complete the following information):**
 - Device: [Samsung Galaxy s24+]
 - OS: [ Android 14]
 - Root status [not Rooted -]
 - SD Maid 2/SE version [0.20.0 beta0]

* 

**Screenshots/Video**
Not able to screen shot bcs  the app quit at once

**Comment by dancorpse** [comment] 2024-02-18 01:47
Uploading VID_20240218_092433_01.mp4…

**Comment by dancorpse** [comment] 2024-02-18 01:49
![IMG_20240218_092328__01](https://github.com/d4rken-org/sdmaid-se/assets/19525152/c026894e-f99d-4666-b5e8-01673604bd22)

**Comment by dancorpse** [comment] 2024-02-18 01:49
https://github.com/d4rken-org/sdmaid-se/assets/19525152/e87bf02d-5de1-470c-9671-368348e0ebb5

**Comment by d4rken** [comment] 2024-02-18 08:17
Please provide a debug log of this:
https://github.com/d4rken-org/sdmaid-se/wiki/Bugs#debug-log

**Comment by dancorpse** [comment] 2024-02-18 10:09
OK, I will try to post the debug log later.

**Comment by dancorpse** [comment] 2024-02-19 05:16
[eu.darken.sdmse_logfile_1708319523690.zip](https://github.com/d4rken-org/sdmaid-se/files/14326645/eu.darken.sdmse_logfile_1708319523690.zip)

**Comment by dancorpse** [comment] 2024-02-19 05:26
Here is the debug log. I noticed that on android 14, there's no selection of grant access to android/data folder under manager storage, but on android 10, there is selection for grant access to android/data folder. I guess this is the reason why  SD maid SE's app cleaner does not work on android 14, how can I grant access to android/data?

**Comment by d4rken** [comment] 2024-02-20 07:52
The issue is with your systems package manager.

This is a "safety crash":

```java
2024-02-19T05:12:14.805Z  E/SDMSE:App: UNCAUGHT EXCEPTION: eu.darken.sdmse.common.pkgs.pkgops.IllegalPkgDataException: No installed packages
	at eu.darken.sdmse.common.pkgs.sources.PackageManagerPkgSource.access$getCoreList(Unknown Source:232)
	at eu.darken.sdmse.common.pkgs.sources.PackageManagerPkgSource$getCoreList$1.invokeSuspend(Unknown Source:11)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:107)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:93)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: 
```

There should never be 0 pkgs, as there are always some system apps installed:

```
D/SDMSE:PkgRepo: 0 pkgs from eu.darken.sdmse.common.pkgs.sources.SystemManifestPkgSource@1dee8be
```

Any idea why this would be? :thinking:

**Comment by dancorpse** [comment] 2024-02-21 03:16
Oh, I'm so stupid that just noticed that I haven't given SD maid SE permission to app list, need to go to setting - app - SD Maid SE and allow permission to app list, the app itself do not pop up ask for permission to app list.

**Comment by d4rken** [comment] 2024-02-21 17:49
Is this a special Samsung only setting? Can you show me a screenshot? :thinking:

**Comment by dancorpse** [comment] 2024-02-22 09:09
Below 2 pictures are from oneplus 7T,  Android 10 phone, there's no permmission for app list: 
![android-10](https://github.com/d4rken-org/sdmaid-se/assets/19525152/d4574eba-05bb-4652-a5f5-476ec51a622a)
![android-10-2](https://github.com/d4rken-org/sdmaid-se/assets/19525152/799d4fbc-6a07-4f1f-9eb7-e9db90afcb25)

Below 2 pictures are from samsung galaxy 24+ phone, Android 14, there's permmission option named app list:
![android 14](https://github.com/d4rken-org/sdmaid-se/assets/19525152/b1dfb001-2a42-46b0-8ce6-a1087903dfa5)
![android 14-2](https://github.com/d4rken-org/sdmaid-se/assets/19525152/b0b87f0b-3347-42eb-b1f9-74938f1789f7)

**Comment by d4rken** [comment] 2024-02-22 11:28
This should have been granted by default, did you manually disable it?

**Comment by d4rken** [comment] 2024-02-24 08:14
This is normally not a permission that can't be taken away. The S24+ is a popular device, if this is not granted by default, then I would expect to get more feedback about crashes 🤷.

I'm closing this for now as there is nothing to do here for me. If we later find out this is a special thing to request on Samsung device, then we reopen it.

Thanks for the report!

> Below 2 pictures are from samsung galaxy 24+ phone, Android 14, there's permmission option named app list:

The permission is new, I think Android 12 or 13+, it's just unusual that it's visible and can be taken away. The permission has to be declared by developer and is automatically granted, but Google Play requires devs to provide an explanation on why the permission is requested.

**Comment by d4rken** [comment] 2024-02-24 08:15
Actually, let's leave this open for now, I'll look into whether SD Maid can handle this without crash and show a setup card with instructions for Samsung devices...

**Comment by d4rken** [comment] 2024-02-25 20:36
Still don't get what Samsung is doing here except, but #1033 will make SD Maid not crash and handle this more gracefully, i.e. show a hint to the user about it.

**Closed** 2024-02-25 21:21 UTC
Labels: enhancement, c: AppCleaner, c: Setup, api: 34 A14 (Upside Down Cake), Device specific
