### ISSUE TITLE
"Error - NullPointerException" dialog appears when clearing cache with AppCleaner

### ISSUE THREAD

**Issue by tfkhdyt** [d4rken-org/sdmaid-se#751] opened 2023-10-22 11:04 UTC
**Describe the bug**
When I clear the cache of an application using the AppCleaner feature, sometimes a "NullPointerException" dialog appears.

**To Reproduce**
1. Press "Scan" button on AppCleaner section
1. Press "eye" icon
1. Choose any app
1. Confirm Deletion -> Delete
1. Wail until its done
1. See error

**Expected behavior**
App's cache cleared without any error dialog

**Smartphone (please complete the following information):**
 - Device: Realme 3 Pro (RMX1851)
 - OS: Android 13 (Lineage 20)
 - Rooted - KernelSU v0.6.9
 - v0.15.3-beta0

**Debug log**
[eu.darken.sdmse_logfile_1697971924522.log.zip](https://github.com/d4rken-org/sdmaid-se/files/13063030/eu.darken.sdmse_logfile_1697971924522.log.zip)

**Screenshots/Video**
![NullPointerException](https://github.com/d4rken-org/sdmaid-se/assets/47195537/5d2e8a88-c344-4add-add4-0bb84d7bac53)

**Comment by d4rken** [comment] 2023-10-22 11:12
Any pattern to the apps? Maybe only system apps or only user apps?

**Comment by tfkhdyt** [comment] 2023-10-23 11:19
I don't know, it's completely random.
I only clear user apps.

**Comment by d4rken** [comment] 2023-11-28 14:47
Currently not able to narrow down the cause :(

**Comment by AGA2707** [comment] 2023-12-17 18:06
Same here I taught I was the only one. I'm using a Xiaomi Redmi Note 7, Rooted using Magisk 26400 and paired with SUI. I'm using the Old SD Maid way back year 2015-2016 something on that year on my old device that I can't even remember and same error. SD Maid SE adapt it. And app doesn't even clean that much, out of 600mb cache It only clean 17mb, my stock cleaner can clean even more without root haha.
![Screenshot_2023-12-14-22-35-47-147_eu darken sdmse](https://github.com/d4rken-org/sdmaid-se/assets/148602118/2a8740c8-8daa-447c-9580-9f23d469541a)

**Comment by d4rken** [comment] 2023-12-21 13:24
@HarriBuh See https://github.com/d4rken-org/sdmaid-se/wiki/Bugs#debug-log

**Comment by d4rken** [comment] 2023-12-26 20:19
That it only happened when clearing individual apps got me on the right path.

Will be fixed with the next update.

https://github.com/d4rken-org/sdmaid-se/pull/895/commits/066407f57e64fd5357bd726049144a17c223b752

**Closed** 2023-12-27 08:22 UTC
Labels: bug, c: AppCleaner
