### ISSUE TITLE
Update unavailable in Google Play Store 

### ISSUE THREAD

**Issue by akks1981** [d4rken-org/sdmaid-se#1074] opened 2024-03-19 15:56 UTC
**Describe the bug**
I have the v0.22.0-beta0 as paid Pro Version! Till now No Update to the new Version in the Play Store. A Bug?

**To Reproduce**

**Expected behavior**

**Smartphone (please complete the following information):**
 - Device: [Pixel 6 pro]
 - OS: [e.g. Android 14]
 - Root status [No root]
 - SD Maid 2/SE version [e.g. v0.21-beta0]

**Debug log**

**Screenshots/Video**

**Additional context**

**Comment by d4rken** [comment] 2024-03-19 16:08
Google Play Review is just not fast :shrug: 
![Screenshot from 2024-03-19 17-08-10](https://github.com/d4rken-org/sdmaid-se/assets/1439229/3d32d49a-b340-470b-b897-bfa152c33bc8)

**Comment by d4rken** [comment] 2024-03-20 13:18
Note that Google randomly rejected v0.22.0-beta0 and now we are waiting for the resubmission to be reviewed.

**Comment by cobbAnderson108** [comment] 2024-03-26 01:21
Yet another reason why I don't use the Play Store (I use Aurora Store if I have to). F-Droid is rarely far behind your releases, and Obtanium is a great way to update directly from the releases here.

**Comment by d4rken** [comment] 2024-03-26 14:02
3rd try wasn't the charm 😢 , I'm now in appeals.

**Comment by d4rken** [comment] 2024-03-28 11:56
The appeal was declined. I  have appealed again with more clarifications and videos of all tools showing that they need access to the list of installed applications.

I'm currently guessing that the issue might be that it's purely about the app store description not being explicit enough so you can't deduce from the app store description that SD Maid requires access to the app inventory. :thinking: I'm expecting another appeal decline and am preparing a new app store description... :frowning_face:

**Comment by d4rken** [comment] 2024-03-28 14:55
https://support.google.com/googleplay/android-developer/answer/10158779?hl=en

> Core functionality is defined as the main purpose of the app. Without this core ability to search for all apps on the device, the app is "broken" or becomes unusable. The core functionality, as well as any core features that comprise this core functionality, must all be prominently documented and promoted in the app's description.

:thinking:

**Comment by d4rken** [comment] 2024-03-28 15:07
Apparently the initial email that restates the rejection is not a decline:

> Currently, your appeal is still under review and I appreciate your patience while we are still looking into it. 

I'm preparing a new app store description in any case...

`Walking on egg shells` 

Just Google Play Things :tm:

**Comment by akks1981** [comment] 2024-03-28 15:30
Thank you for your efforts.

**Comment by d4rken** [comment] 2024-03-28 17:39
The new app store description is ready and I've also prepared a new permission declaration and  demo video.

> My app is a file manager specialized in knowing which apps have created specific files. Its core functionality is comparing files and installed apps to help the user free space on their device.
> 
> Its tools match files against apps to get their results:
> 
> AppCleaner finds apps with expendable files.
> CorpseFinder deletes files from uninstalled apps.
> SystemCleaner deletes APK files that are installed.
> AppControl searches and manages installed apps.
> StorageAnalyzer shows storage space usage per app.
 

https://www.youtube.com/watch?v=LoWd0C0MnB4

I've not submitted for review again. I'll wait for the appeal result first. If the appeal is negative, I'll submit again with new app store texts. I really hope that if the appeal is negative that they at least point out that the issue is with the app store text so I'm less in the dark.

**Comment by d4rken** [comment] 2024-04-06 11:53
Send `0.23.3-beta0` to review with the new description :pray:

**Comment by GlassedSilver** [comment] 2024-04-06 23:40
I bought Pro on the Play Store, any way to switch to F-Droid release keeping my settings AND my Pro license? Having to wait for Google to review AND like what you're doing is probably going to remain an ever worsening issue... :S

**Comment by d4rken** [comment] 2024-04-09 08:40
> I bought Pro on the Play Store, any way to switch to F-Droid release keeping my settings AND my Pro license? Having to wait for Google to review AND like what you're doing is probably going to remain an ever worsening issue... :S

You have to reinstall due to different signatures, but the FOSS pro upgrade is based on honor, so technically, you wouldn't have to pay again.

**Comment by d4rken** [comment] 2024-04-09 14:50
`0.23.3-beta0` has been approved and is available on Google Play, let's close this again... for now :man_shrugging: :massage:.

**Closed by d4rken** 2024-04-09 14:50 UTC
Labels: Google Play

**Comment by akks1981** [comment] 2024-08-16 15:06
Till now No new Update at the Google Play Store. Still Version 1.2.2

**Comment by d4rken** [comment] 2024-08-16 15:25
Google review took a while and I was busy with other stuff. I just pushed it through. Should become available on the test track today.

**Comment by akks1981** [comment] 2024-08-16 19:34
Update is working now. Thank you

**Comment by krystian3w** [comment] 2025-03-31 10:06
Any chance to disable see beta in Aurora Nighty with guest accounts?

![Image](https://github.com/user-attachments/assets/45504d5a-d61f-4aee-add8-4a14f811fed6)

https://www.reddit.com/r/degoogle/comments/1hy8qfx/question_about_aurora_store_check_updates/

Supposedly Aurora without an account does not have access to the beta channel.

**Comment by akks1981** [comment] 2025-03-31 12:08
No new Update at the Google Play Store. Still Version v1.3.6-rc0 and not the Version v1.4.1-beta0

**Comment by krystian3w** [comment] 2025-03-31 12:34
But somehow, Aurora's Guest account got added to the Play Store beta program:

> ![Image](https://github.com/user-attachments/assets/b7f9ef86-6507-45f1-abfa-a3cdd52fe985)
