### ISSUE TITLE
Feature Request: Duplicates Finder

### ISSUE THREAD

**Issue by L31FY** [d4rken-org/sdmaid-se#248] opened 2023-05-05 23:51 UTC
The previous version of the app had a duplicates finder I found very useful as sometimes you forget you saved that meme already or a download fails but retries and you end up with the original resuming to completion and a second copy also just as examples I personally had. I would hugely appreciate if that could be brought into this new version as well. Right now I still find myself using it because it is just that useful, but I'd like to fully migrate to this version due to better storage clearing capabilities on my newer Android software version. I would like to end by thanking you for your work and I have once again supported your app because it is one I find myself needing to have as many apps I have run better having their clutter cleared out every so often.

**Comment by d4rken** [comment] 2023-05-07 10:29
Duplicate of #2 😉

**Closed by d4rken** 2023-05-07 10:29 UTC
Labels: enhancement, triage
