### ISSUE TITLE
Still not completing cleaning

### ISSUE THREAD

**Issue by Taz112768** [d4rken-org/sdmaid-se#682] opened 2023-10-02 12:55 UTC
Click scan wait for completion get results click delete still doesn't delete all info it lists as deletable and does not clean or delete them all.
![Screenshot_20231002-085118](https://github.com/d4rken-org/sdmaid-se/assets/68667867/799708d2-dcb7-4485-811d-a14abb8b3d28)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 9]
 - OS: [e.g. Android 17]
 - Root status [e.g. Rooted - Magisk v25.2]
 - SD Maid 2/SE version [e.g. v0.6.6-rc6]

**Debug log**
If you can reproduce the bug, record the event in [a debug log](https://github.com/d4rken-org/sdmaid-se/wiki/Bugs#debug-log).

**Screenshots/Video**
If applicable, add screenshots or a video if it helps to explain your problem.

**Additional context**

**Comment by d4rken** [comment] 2023-10-02 23:39
Please provide a debug log.

But also note that without root, if the remaining files are part of the default caches, then it's the system not deleting all caches and I'm not sure this can be solved, as SD Maid only presses "clear cache" and can't access these files directly.

**Comment by 5uck3rpunch** [comment] 2023-10-04 18:51
Same issue for me also on One UI 5 on a Samsung Galaxy Z Fold 4.  I gave the app all permissions it required but I do not get prompted for Permissions for System Cleaner.

**Comment by MeloriTensei** [comment] 2023-10-09 15:05
@Taz112768 @5uck3rpunch 
Hi, just as Darken, the dev, says, cleaner apps on Android are not perfect as they only do what they could reach.  Even if you try to clear the cache by hand, you'll still get the same result if the said caches are undeletable, the 0kb could possibly also be an illusion and it would return to the same state when you reopen that screen.

Android can sometimes be weird imho.

**Comment by Taz112768** [comment] 2023-10-09 15:15
Yea I have a cheaper end phone I been using your first product will continue to use this one. I haven't rooted yet and it's a small issue. Thanks for response though.On Oct 9, 2023 11:05 AM, ♡M3L0R1T3NSE1♡ ***@***.***> wrote:
@Taz112768 @5uck3rpunch
Hi, just as Darken, the dev, says, cleaner apps on Android are not perfect as they only do what they could reach.  Even if you try to clear the cache by hand, you'll still get the same result if the said caches are undeletable, the 0kb could possibly also be an illusion and it would return to the same state when you reopen that screen.
Android can sometimes be weird imho.

**Comment by d4rken** [comment] 2023-10-09 15:32
Duplicate of #588

Closing this to keep information in one place.

**Closed by d4rken** 2023-10-09 15:32 UTC
Labels: bug, needs info/repro 🤔, c: AppCleaner
